<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>

                require([
                         'Magento_Customer/js/customer-data'
                     ], function (customerData) {
                         var sections = ['cart'];
                         customerData.invalidate(sections);
                     });


</script>